/* Generated By:JJTree&JavaCC: Do not edit this line. HtScrapeConstants.java */
package wci.frontend;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HtScrapeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING_LITERAL = 7;
  /** RegularExpression Id. */
  int CHARACTER = 8;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int THEN = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int EXIT = 15;
  /** RegularExpression Id. */
  int THROW = 16;
  /** RegularExpression Id. */
  int BREAK = 17;
  /** RegularExpression Id. */
  int VOID = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int INT = 20;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int TRUE = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int TRY = 24;
  /** RegularExpression Id. */
  int CATCH = 25;
  /** RegularExpression Id. */
  int FOR = 26;
  /** RegularExpression Id. */
  int NULL = 27;
  /** RegularExpression Id. */
  int GET = 28;
  /** RegularExpression Id. */
  int PRINT = 29;
  /** RegularExpression Id. */
  int PRINT_FULL_TABLE = 30;
  /** RegularExpression Id. */
  int PRINT_DATA = 31;
  /** RegularExpression Id. */
  int IDENTIFIER = 32;
  /** RegularExpression Id. */
  int LEFT_PAREN = 33;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 34;
  /** RegularExpression Id. */
  int LEFT_CURLY = 35;
  /** RegularExpression Id. */
  int RIGHT_CURLY = 36;
  /** RegularExpression Id. */
  int PLUS = 37;
  /** RegularExpression Id. */
  int MINUS = 38;
  /** RegularExpression Id. */
  int MULTIPLY = 39;
  /** RegularExpression Id. */
  int DIVIDE = 40;
  /** RegularExpression Id. */
  int EQUALS = 41;
  /** RegularExpression Id. */
  int LESS_THAN = 42;
  /** RegularExpression Id. */
  int GREATER_THAN = 43;
  /** RegularExpression Id. */
  int BANG = 44;
  /** RegularExpression Id. */
  int COMMA = 45;
  /** RegularExpression Id. */
  int PERIOD = 46;
  /** RegularExpression Id. */
  int SEMICOLON = 47;
  /** RegularExpression Id. */
  int AT_SIGN = 48;
  /** RegularExpression Id. */
  int POUND_SIGN = 49;
  /** RegularExpression Id. */
  int LETTER = 50;
  /** RegularExpression Id. */
  int DIGIT = 51;
  /** RegularExpression Id. */
  int LESS_EQUAL = 52;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 53;
  /** RegularExpression Id. */
  int DOUBLE_EQUAL = 54;
  /** RegularExpression Id. */
  int NOT_EQUAL = 55;
  /** RegularExpression Id. */
  int PLUS_PLUS = 56;
  /** RegularExpression Id. */
  int PLUS_EQUAL = 57;
  /** RegularExpression Id. */
  int MINUS_EQUAL = 58;
  /** RegularExpression Id. */
  int MULTIPLY_EQUAL = 59;
  /** RegularExpression Id. */
  int DIVIDE_EQUAL = 60;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<STRING_LITERAL>",
    "<CHARACTER>",
    "<INTEGER>",
    "<NUMBER>",
    "\"if\"",
    "\"else\"",
    "\"then\"",
    "\"while\"",
    "\"exit\"",
    "\"throw\"",
    "\"break\"",
    "\"void\"",
    "\"return\"",
    "\"int\"",
    "\"string\"",
    "\"true\"",
    "\"false\"",
    "\"try\"",
    "\"catch\"",
    "\"for\"",
    "\"null\"",
    "\"get\"",
    "\"print\"",
    "\"printFullTable\"",
    "\"printData\"",
    "<IDENTIFIER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"!\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"@\"",
    "\"#\"",
    "<LETTER>",
    "<DIGIT>",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"++\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
  };

}
