/* Generated By:JavaCC: Do not edit this line. HtScrapeDefaultVisitor.java Version 6.0_1 */
package wci.frontend;

public class HtScrapeDefaultVisitor implements HtScrapeVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProgram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvariable node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTnewVariable node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntDeclaration node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNumberDeclaration node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArithmeticStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTlookahead node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTlookahead2 node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSimpleAssignment node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTComplexAssignment node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStringDeclaration node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMultipleParams node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPrintStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPrintFullTableStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPrintDataStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIfStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhileStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOperator node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOperand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTexpr_operator node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTarith_operator node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTintegerConstant node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTnumberConstant node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTstringConstant node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=5637dd00ad01bd3f70dfac9930d50c2a (do not edit this line) */
