/* Generated By:JavaCC: Do not edit this line. HtScrapeTreeConstants.java Version 6.0_1 */
package wci.frontend;

public interface HtScrapeTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT = 1;
  public int JJTVARIABLE = 2;
  public int JJTNEWVARIABLE = 3;
  public int JJTINTDECLARATION = 4;
  public int JJTNUMBERDECLARATION = 5;
  public int JJTARITHMETICSTATEMENT = 6;
  public int JJTLOOKAHEAD = 7;
  public int JJTLOOKAHEAD2 = 8;
  public int JJTSIMPLEASSIGNMENT = 9;
  public int JJTCOMPLEXASSIGNMENT = 10;
  public int JJTSTRINGDECLARATION = 11;
  public int JJTMULTIPLEPARAMS = 12;
  public int JJTPRINTSTATEMENT = 13;
  public int JJTPRINTFULLTABLESTATEMENT = 14;
  public int JJTPRINTDATASTATEMENT = 15;
  public int JJTIFSTATEMENT = 16;
  public int JJTWHILESTATEMENT = 17;
  public int JJTEXPRESSION = 18;
  public int JJTOPERATOR = 19;
  public int JJTOPERAND = 20;
  public int JJTEXPR_OPERATOR = 21;
  public int JJTARITH_OPERATOR = 22;
  public int JJTINTEGERCONSTANT = 23;
  public int JJTNUMBERCONSTANT = 24;
  public int JJTSTRINGCONSTANT = 25;
  public int JJTVOID = 26;


  public String[] jjtNodeName = {
    "Program",
    "Statement",
    "variable",
    "newVariable",
    "IntDeclaration",
    "NumberDeclaration",
    "ArithmeticStatement",
    "lookahead",
    "lookahead2",
    "SimpleAssignment",
    "ComplexAssignment",
    "StringDeclaration",
    "MultipleParams",
    "PrintStatement",
    "PrintFullTableStatement",
    "PrintDataStatement",
    "IfStatement",
    "WhileStatement",
    "Expression",
    "Operator",
    "Operand",
    "expr_operator",
    "arith_operator",
    "integerConstant",
    "numberConstant",
    "stringConstant",
    "void",
  };
}
/* JavaCC - OriginalChecksum=daf873d6519d385c2124396254b1f587 (do not edit this line) */
