/* Generated By:JavaCC: Do not edit this line. HtScrapeVisitor.java Version 5.0 */
package wci.frontend;

public interface HtScrapeVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTvariable node, Object data);
  public Object visit(ASTnewVariable node, Object data);
  public Object visit(ASTIntDeclaration node, Object data);
  public Object visit(ASTNumberDeclaration node, Object data);
  public Object visit(ASTArithmeticStatement node, Object data);
  public Object visit(ASTlookahead node, Object data);
  public Object visit(ASTlookahead2 node, Object data);
  public Object visit(ASTSimpleAssignment node, Object data);
  public Object visit(ASTComplexAssignment node, Object data);
  public Object visit(ASTStringDeclaration node, Object data);
  public Object visit(ASTMultipleParams node, Object data);
  public Object visit(ASTPrintStatement node, Object data);
  public Object visit(ASTPrintFullTableStatement node, Object data);
  public Object visit(ASTPrintDataStatement node, Object data);
  public Object visit(ASTGetDataStatement node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTElseStatement node, Object data);
  public Object visit(ASTWhileStatement node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTOperator node, Object data);
  public Object visit(ASTOperand node, Object data);
  public Object visit(ASTexpr_operator node, Object data);
  public Object visit(ASTarith_operator node, Object data);
  public Object visit(ASTintegerConstant node, Object data);
  public Object visit(ASTnumberConstant node, Object data);
  public Object visit(ASTstringConstant node, Object data);
}
/* JavaCC - OriginalChecksum=e26c4b99bdd034eab4101cc8fcaa50eb (do not edit this line) */
