/* Generated By:JavaCC: Do not edit this line. HtScrapeTreeConstants.java Version 5.0 */
package wci.frontend;

public interface HtScrapeTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT = 1;
  public int JJTVARIABLE = 2;
  public int JJTNEWVARIABLE = 3;
  public int JJTINTDECLARATION = 4;
  public int JJTSIMPLEASSIGNMENT = 5;
  public int JJTCOMPLEXASSIGNMENT = 6;
  public int JJTSTRINGDECLARATION = 7;
  public int JJTFILEDECLARATION = 8;
  public int JJTLOADSTATEMENT = 9;
  public int JJTTABLEDECLARATION = 10;
  public int JJTGETTABLESTATEMENT = 11;
  public int JJTTABLEDATADECLARATION = 12;
  public int JJTGETTABLEDATASTATEMENT = 13;
  public int JJTCOLORDECLARATION = 14;
  public int JJTGETCOLORSTATEMENT = 15;
  public int JJTMULTIPLEPARAMS = 16;
  public int JJTPRINTSTATEMENT = 17;
  public int JJTCLOSESTATEMENT = 18;
  public int JJTIFSTATEMENT = 19;
  public int JJTEXPRESSION = 20;
  public int JJTOPERATOR = 21;
  public int JJTOPERAND = 22;
  public int JJTEXPR_OPERATOR = 23;
  public int JJTINTEGERCONSTANT = 24;
  public int JJTSTRINGCONSTANT = 25;
  public int JJTVOID = 26;


  public String[] jjtNodeName = {
    "Program",
    "Statement",
    "variable",
    "newVariable",
    "IntDeclaration",
    "SimpleAssignment",
    "ComplexAssignment",
    "StringDeclaration",
    "FileDeclaration",
    "LoadStatement",
    "TableDeclaration",
    "GetTableStatement",
    "TableDataDeclaration",
    "GetTableDataStatement",
    "ColorDeclaration",
    "GetColorStatement",
    "MultipleParams",
    "PrintStatement",
    "CloseStatement",
    "IfStatement",
    "Expression",
    "Operator",
    "Operand",
    "expr_operator",
    "integerConstant",
    "stringConstant",
    "void",
  };
}
/* JavaCC - OriginalChecksum=4f29aec2a1a96d4b9a76c502ec47f0de (do not edit this line) */
