/* Generated By:JavaCC: Do not edit this line. HtScrapeTreeConstants.java Version 5.0 */
package wci.frontend;

public interface HtScrapeTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTATEMENT = 1;
  public int JJTINTDECLARATION = 2;
  public int JJTSIMPLEASSIGNMENT = 3;
  public int JJTSTRINGDECLARATION = 4;
  public int JJTFILEDECLARATION = 5;
  public int JJTLOADSTATEMENT = 6;
  public int JJTTABLEDECLARATION = 7;
  public int JJTGETTABLESTATEMENT = 8;
  public int JJTTABLEDATADECLARATION = 9;
  public int JJTGETTABLEDATASTATEMENT = 10;
  public int JJTCOLORDECLARATION = 11;
  public int JJTGETCOLORSTATEMENT = 12;
  public int JJTMULTIPLEPARAMS = 13;
  public int JJTPRINTSTATEMENT = 14;
  public int JJTCLOSESTATEMENT = 15;
  public int JJTIFSTATEMENT = 16;
  public int JJTEXPRESSION = 17;
  public int JJTOPERATOR = 18;
  public int JJTOPERAND = 19;
  public int JJTEXPR_OPERATOR = 20;
  public int JJTVOID = 21;


  public String[] jjtNodeName = {
    "Program",
    "Statement",
    "IntDeclaration",
    "SimpleAssignment",
    "StringDeclaration",
    "FileDeclaration",
    "LoadStatement",
    "TableDeclaration",
    "GetTableStatement",
    "TableDataDeclaration",
    "GetTableDataStatement",
    "ColorDeclaration",
    "GetColorStatement",
    "MultipleParams",
    "PrintStatement",
    "CloseStatement",
    "IfStatement",
    "Expression",
    "Operator",
    "Operand",
    "expr_operator",
    "void",
  };
}
/* JavaCC - OriginalChecksum=6dc0f6df61c65e9fec5bdfb111d0908a (do not edit this line) */
