/* Generated By:JJTree&JavaCC: Do not edit this line. HtScrapeConstants.java */
package wci.frontend;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HtScrapeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING_LITERAL = 7;
  /** RegularExpression Id. */
  int CHARACTER = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int THEN = 12;
  /** RegularExpression Id. */
  int EXIT = 13;
  /** RegularExpression Id. */
  int THROW = 14;
  /** RegularExpression Id. */
  int BREAK = 15;
  /** RegularExpression Id. */
  int VOID = 16;
  /** RegularExpression Id. */
  int RETURN = 17;
  /** RegularExpression Id. */
  int INT = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;
  /** RegularExpression Id. */
  int STRING = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int TRY = 23;
  /** RegularExpression Id. */
  int CATCH = 24;
  /** RegularExpression Id. */
  int FOR = 25;
  /** RegularExpression Id. */
  int NULL = 26;
  /** RegularExpression Id. */
  int TABLE = 27;
  /** RegularExpression Id. */
  int TABLE_DATA = 28;
  /** RegularExpression Id. */
  int COLOR = 29;
  /** RegularExpression Id. */
  int GET = 30;
  /** RegularExpression Id. */
  int PRINT = 31;
  /** RegularExpression Id. */
  int CLOSE = 32;
  /** RegularExpression Id. */
  int FILE = 33;
  /** RegularExpression Id. */
  int LOAD = 34;
  /** RegularExpression Id. */
  int GET_TABLE = 35;
  /** RegularExpression Id. */
  int GET_DATA = 36;
  /** RegularExpression Id. */
  int GET_COLOR = 37;
  /** RegularExpression Id. */
  int IDENTIFIER = 38;
  /** RegularExpression Id. */
  int LEFT_PAREN = 39;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 40;
  /** RegularExpression Id. */
  int LEFT_CURLY = 41;
  /** RegularExpression Id. */
  int RIGHT_CURLY = 42;
  /** RegularExpression Id. */
  int PLUS = 43;
  /** RegularExpression Id. */
  int MINUS = 44;
  /** RegularExpression Id. */
  int EQUALS = 45;
  /** RegularExpression Id. */
  int LESS_THAN = 46;
  /** RegularExpression Id. */
  int GREATER_THAN = 47;
  /** RegularExpression Id. */
  int BANG = 48;
  /** RegularExpression Id. */
  int COMMA = 49;
  /** RegularExpression Id. */
  int PERIOD = 50;
  /** RegularExpression Id. */
  int SEMICOLON = 51;
  /** RegularExpression Id. */
  int AT_SIGN = 52;
  /** RegularExpression Id. */
  int POUND_SIGN = 53;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<STRING_LITERAL>",
    "<CHARACTER>",
    "<DIGIT>",
    "\"if\"",
    "\"else\"",
    "\"then\"",
    "\"exit\"",
    "\"throw\"",
    "\"break\"",
    "\"void\"",
    "\"return\"",
    "\"int\"",
    "\"number\"",
    "\"string\"",
    "\"true\"",
    "\"false\"",
    "\"try\"",
    "\"catch\"",
    "\"for\"",
    "\"null\"",
    "\"table\"",
    "\"table_data\"",
    "\"color\"",
    "\"get\"",
    "\"print\"",
    "\"close\"",
    "\"file\"",
    "\"load\"",
    "\"getTable\"",
    "\"getData\"",
    "\"getColor\"",
    "<IDENTIFIER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"!\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"@\"",
    "\"#\"",
  };

}
