/* Generated By:JavaCC: Do not edit this line. HtScrapeVisitor.java Version 5.0 */
package wci.frontend;

public interface HtScrapeVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTIntDeclaration node, Object data);
  public Object visit(ASTSimpleAssignment node, Object data);
  public Object visit(ASTStringDeclaration node, Object data);
  public Object visit(ASTFileDeclaration node, Object data);
  public Object visit(ASTLoadStatement node, Object data);
  public Object visit(ASTTableDeclaration node, Object data);
  public Object visit(ASTGetTableStatement node, Object data);
  public Object visit(ASTTableDataDeclaration node, Object data);
  public Object visit(ASTGetTableDataStatement node, Object data);
  public Object visit(ASTColorDeclaration node, Object data);
  public Object visit(ASTGetColorStatement node, Object data);
  public Object visit(ASTMultipleParams node, Object data);
  public Object visit(ASTPrintStatement node, Object data);
  public Object visit(ASTCloseStatement node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTOperator node, Object data);
  public Object visit(ASTOperand node, Object data);
  public Object visit(ASTexpr_operator node, Object data);
}
/* JavaCC - OriginalChecksum=31432a1e96579eea3d263649ec6310ca (do not edit this line) */
