/* Generated By:JJTree&JavaCC: Do not edit this line. HtScrapeConstants.java */
package wci.frontend;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HtScrapeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 7;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 8;
  /** RegularExpression Id. */
  int HEX_LITERAL = 9;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 10;
  /** RegularExpression Id. */
  int STRING_LITERAL = 11;
  /** RegularExpression Id. */
  int CHARACTER = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int THEN = 16;
  /** RegularExpression Id. */
  int EXIT = 17;
  /** RegularExpression Id. */
  int THROW = 18;
  /** RegularExpression Id. */
  int BREAK = 19;
  /** RegularExpression Id. */
  int VOID = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int INT = 22;
  /** RegularExpression Id. */
  int NUMBER = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int TRUE = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int TRY = 27;
  /** RegularExpression Id. */
  int CATCH = 28;
  /** RegularExpression Id. */
  int FOR = 29;
  /** RegularExpression Id. */
  int NULL = 30;
  /** RegularExpression Id. */
  int TABLE = 31;
  /** RegularExpression Id. */
  int TABLE_DATA = 32;
  /** RegularExpression Id. */
  int COLOR = 33;
  /** RegularExpression Id. */
  int GET = 34;
  /** RegularExpression Id. */
  int PRINT = 35;
  /** RegularExpression Id. */
  int CLOSE = 36;
  /** RegularExpression Id. */
  int FILE = 37;
  /** RegularExpression Id. */
  int LOAD = 38;
  /** RegularExpression Id. */
  int GET_TABLE = 39;
  /** RegularExpression Id. */
  int GET_DATA = 40;
  /** RegularExpression Id. */
  int GET_COLOR = 41;
  /** RegularExpression Id. */
  int IDENTIFIER = 42;
  /** RegularExpression Id. */
  int LEFT_PAREN = 43;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 44;
  /** RegularExpression Id. */
  int LEFT_CURLY = 45;
  /** RegularExpression Id. */
  int RIGHT_CURLY = 46;
  /** RegularExpression Id. */
  int PLUS = 47;
  /** RegularExpression Id. */
  int MINUS = 48;
  /** RegularExpression Id. */
  int EQUALS = 49;
  /** RegularExpression Id. */
  int LESS_THAN = 50;
  /** RegularExpression Id. */
  int GREATER_THAN = 51;
  /** RegularExpression Id. */
  int BANG = 52;
  /** RegularExpression Id. */
  int COMMA = 53;
  /** RegularExpression Id. */
  int PERIOD = 54;
  /** RegularExpression Id. */
  int SEMICOLON = 55;
  /** RegularExpression Id. */
  int AT_SIGN = 56;
  /** RegularExpression Id. */
  int POUND_SIGN = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<STRING_LITERAL>",
    "<CHARACTER>",
    "<DIGIT>",
    "\"if\"",
    "\"else\"",
    "\"then\"",
    "\"exit\"",
    "\"throw\"",
    "\"break\"",
    "\"void\"",
    "\"return\"",
    "\"int\"",
    "\"number\"",
    "\"string\"",
    "\"true\"",
    "\"false\"",
    "\"try\"",
    "\"catch\"",
    "\"for\"",
    "\"null\"",
    "\"table\"",
    "\"table_data\"",
    "\"color\"",
    "\"get\"",
    "\"print\"",
    "\"close\"",
    "\"file\"",
    "\"load\"",
    "\"getTable\"",
    "\"getData\"",
    "\"getColor\"",
    "<IDENTIFIER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"!\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"@\"",
    "\"#\"",
  };

}
